# Generated by Django 5.0 on 2025-06-25 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VORDCAB', 'VORDCAB'), ('PROVEEDOR', 'Proveedor'), ('VACIO', 'Vacío')], max_length=10)),
                ('solicitud', models.CharField(max_length=20)),
                ('id_detalle', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto_flujo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('proveedor', models.ForeignKey(blank=True, help_text='Solo se llena si el tipo es PROVEEDOR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.proveedor')),
            ],
        ),
    ]
