# Generated by Django 5.0 on 2025-06-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_exhibit_proveedor_delete_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='tipo',
            field=models.CharField(choices=[('Vordcab', 'Vordcab'), ('PROVEEDOR', 'Proveedor'), ('VACIO', 'Vacío')], max_length=10),
        ),
    ]
