# Generated by Django 5.0 on 2025-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_remove_exhibit_concepto_flujo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
