# Generated by Django 5.0 on 2025-07-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_exhibit_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_exhibit',
            name='exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.exhibit'),
        ),
    ]
