# Generated by Django 5.0 on 2025-07-16 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_linea_exhibit_exhibit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago_Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='tipo_pago_exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipo_pago_exhibit'),
        ),
    ]
