# Generated by Django 5.0 on 2025-07-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_tipo_pago_exhibit_linea_exhibit_tipo_pago_exhibit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_exhibit',
            name='concepto_flujo',
        ),
    ]
