# Generated by Django 5.0 on 2025-07-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_remove_linea_exhibit_concepto_flujo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_exhibit',
            name='nombre_proveedor',
        ),
    ]
