# Generated by Django 5.0 on 2025-07-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_remove_linea_exhibit_nombre_proveedor'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_exhibit',
            name='aba',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.banco'),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='clabe',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='colonia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='contacto_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='cuenta_bancaria',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='direccion_banco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='iban',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='moneda',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='observaciones_cuenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='swift',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='linea_exhibit',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
