# Generated by Django 5.0 on 2025-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_linea_exhibit_aba_linea_exhibit_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_exhibit',
            name='tipo_proveedor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
