# Generated by Django 5.0 on 2025-07-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_linea_exhibit_tipo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_exhibit',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
