# Generated by Django 5.0 on 2025-07-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0061_compra_comentario_cierre_and_more'),
        ('finanzas', '0012_linea_exhibit_pagina_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_exhibit',
            name='moneda',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='compras.moneda'),
        ),
    ]
