# Generated by Django 5.0 on 2025-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_alter_linea_exhibit_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_exhibit',
            name='tipo_proveedor',
            field=models.CharField(blank=True, choices=[('PM', 'Persona Moral'), ('PF', 'Persona Física')], help_text='Selecciona si el proveedor es una Persona Moral (PM) o Física (PF)', max_length=2, null=True),
        ),
    ]
