# Generated by Django 5.0 on 2025-09-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0072_remove_debida_diligencia_elaborado_por'),
        ('solicitudes', '0008_contrato_complete_contrato_created_at_and_more'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_unidad', models.CharField(max_length=100, null=True)),
                ('mes_inicial', models.DateField()),
                ('mes_final', models.DateField()),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones_contratos', to='solicitudes.contrato')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones_distritos', to='user.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_contratos', to='solicitudes.contrato')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_distritos', to='user.distrito')),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorizacion', models.CharField(max_length=150, null=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_conceptos', to='rentabilidad.concepto')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_contratos', to='solicitudes.contrato')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_distritos', to='user.distrito')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_tipos', to='rentabilidad.tipo_costo')),
            ],
        ),
    ]
