# Generated by Django 5.0 on 2025-09-09 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0001_initial'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='costos',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='costos',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costo_created', to='user.profile'),
        ),
    ]
