# Generated by Django 5.0 on 2025-09-10 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0002_costos_created_at_costos_created_by'),
        ('solicitudes', '0008_contrato_complete_contrato_created_at_and_more'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costos',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='costos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='costos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='costos',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='costos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='depreciaciones',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='depreciaciones',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='costos',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depreciaciones',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Solicitud_Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('fecha', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_contratos', to='solicitudes.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_created', to='user.profile')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_distritos', to='user.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('fecha', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_contratos', to='solicitudes.contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_created', to='user.profile')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='si_distritos', to='user.distrito')),
            ],
        ),
    ]
