# Generated by Django 5.0 on 2025-09-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0003_remove_costos_contrato_remove_costos_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='solicitud_costos',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_tipos', to='rentabilidad.tipo_costo'),
        ),
    ]
