# Generated by Django 5.0 on 2025-09-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0004_remove_costos_tipo_solicitud_costos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='costos',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='rentabilidad.solicitud_costos'),
        ),
    ]
