# Generated by Django 5.0 on 2025-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0005_costos_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_costos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
