# Generated by Django 5.0 on 2025-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0006_alter_solicitud_costos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_ingresos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
