# Generated by Django 5.0 on 2025-09-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0007_alter_solicitud_ingresos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='rentabilidad.solicitud_ingresos'),
        ),
    ]
