# Generated by Django 5.0 on 2025-09-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0008_ingresos_solicitud'),
        ('solicitudes', '0008_contrato_complete_contrato_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_ingresos',
            name='contrato',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_contratos', to='solicitudes.contrato'),
        ),
    ]
