# Generated by Django 5.0 on 2025-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0009_remove_solicitud_ingresos_contrato_ingresos_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='concepto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
