# Generated by Django 5.0 on 2025-09-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0010_alter_ingresos_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depreciaciones',
            name='mes_final',
        ),
        migrations.AddField(
            model_name='depreciaciones',
            name='mesas_a_depreciar',
            field=models.IntegerField(null=True),
        ),
    ]
