# Generated by Django 5.0 on 2025-09-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0011_remove_depreciaciones_mes_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depreciaciones',
            old_name='mesas_a_depreciar',
            new_name='meses_a_depreciar',
        ),
    ]
