# Generated by Django 5.0 on 2025-09-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0012_rename_mesas_a_depreciar_depreciaciones_meses_a_depreciar'),
        ('solicitudes', '0008_contrato_complete_contrato_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciaciones',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_contratos', to='solicitudes.contrato'),
        ),
    ]
