# Generated by Django 5.0 on 2025-09-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0013_depreciaciones_contrato'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciaciones',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_distritos', to='user.distrito'),
        ),
    ]
