# Generated by Django 5.0 on 2025-09-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0014_depreciaciones_distrito'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciaciones',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_created', to='user.profile'),
        ),
    ]
