# Generated by Django 5.0 on 2025-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0015_depreciaciones_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciaciones',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
