# Generated by Django 5.0 on 2025-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0016_depreciaciones_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciaciones',
            name='mes_inicial',
            field=models.DateField(null=True),
        ),
    ]
