# Generated by Django 5.0 on 2026-01-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0017_alter_depreciaciones_mes_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costos',
            name='comentario',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
