# Generated by Django 4.2.4 on 2023-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_viatico',
            name='approved_at_time',
        ),
        migrations.RemoveField(
            model_name='solicitud_viatico',
            name='approved_at_time2',
        ),
        migrations.RemoveField(
            model_name='solicitud_viatico',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='solicitud_viatico',
            name='fecha_retorno',
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='periodo_comision',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='approved_at2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='comentario',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='fecha_partida',
            field=models.DateTimeField(null=True),
        ),
    ]
