# Generated by Django 4.2.4 on 2023-10-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('viaticos', '0002_remove_solicitud_viatico_approved_at_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='comentario_hospedaje',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
    ]
