# Generated by Django 4.2.4 on 2023-10-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0004_solicitud_viatico_fecha_inicio_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='lugar_comision',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
