# Generated by Django 4.2.4 on 2023-10-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activo_codigo_alter_activo_cuenta_contable_and_more'),
        ('viaticos', '0009_alter_solicitud_viatico_lugar_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
