# Generated by Django 4.2.4 on 2023-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0010_alter_concepto_viatico_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='precio',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='concepto_viatico',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
