# Generated by Django 4.2.4 on 2023-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0011_alter_concepto_viatico_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
