# Generated by Django 4.2.4 on 2023-10-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0012_alter_concepto_viatico_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaticos_factura',
            name='hora_subido',
        ),
        migrations.AlterField(
            model_name='viaticos_factura',
            name='fecha_subido',
            field=models.DateTimeField(null=True),
        ),
    ]
