# Generated by Django 4.2.4 on 2023-10-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0013_remove_viaticos_factura_hora_subido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticos_factura',
            name='concepto_viatico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.solicitud_viatico'),
        ),
    ]
