# Generated by Django 4.2.4 on 2023-10-27 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0015_rename_concepto_viatico_viaticos_factura_solicitud_viatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticos_factura',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturastb', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='viaticos_factura',
            name='factura_xml',
            field=models.FileField(blank=True, null=True, upload_to='xmltb', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
