# Generated by Django 5.0 on 2024-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0017_rename_fecha_inicio_comision_solicitud_viatico_fecha_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos_intermedios',
            name='comentario_hospedaje',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='puntos_intermedios',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='puntos_intermedios',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
