# Generated by Django 5.0 on 2024-01-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0018_puntos_intermedios_comentario_hospedaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_viatico',
            old_name='comentario',
            new_name='comentario_general',
        ),
        migrations.RenameField(
            model_name='solicitud_viatico',
            old_name='comentario_hospedaje',
            new_name='comentario_jefe_inmediato',
        ),
    ]
