# Generated by Django 5.0 on 2024-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0019_rename_comentario_solicitud_viatico_comentario_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='folio',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
