# Generated by Django 5.0 on 2024-01-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0020_alter_solicitud_viatico_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='folio',
            field=models.IntegerField(null=True),
        ),
    ]
