# Generated by Django 5.0 on 2024-01-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('viaticos', '0021_alter_solicitud_viatico_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='gerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutorizacionG', to='user.profile'),
        ),
    ]
