# Generated by Django 5.0 on 2024-01-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0022_solicitud_viatico_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='motivo',
            field=models.TextField(null=True),
        ),
    ]
