# Generated by Django 5.0.1 on 2024-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0025_alter_concepto_viatico_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='comentarios_cancelacion',
            field=models.TextField(null=True),
        ),
    ]
