# Generated by Django 5.0 on 2024-07-12 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0026_solicitud_viatico_comentarios_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticos_factura',
            name='solicitud_viatico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='viaticos.solicitud_viatico'),
        ),
    ]
