# Generated by Django 5.0.1 on 2024-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0027_alter_viaticos_factura_solicitud_viatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaticos_factura',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaticos_factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
