# Generated by Django 5.0 on 2024-09-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0028_viaticos_factura_fecha_timbrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticos_factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
