# Generated by Django 5.0.1 on 2024-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0029_alter_viaticos_factura_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaticos_factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
