# Generated by Django 5.0 on 2024-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0030_alter_viaticos_factura_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaticos_factura',
            name='autorizada',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
