# Generated by Django 5.0 on 2024-10-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
        ('viaticos', '0031_viaticos_factura_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaticos_factura',
            name='autorizada_el',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='viaticos_factura',
            name='autorizada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizado_factura', to='user.profile'),
        ),
    ]
