# Generated by Django 5.0 on 2024-10-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
        ('viaticos', '0032_viaticos_factura_autorizada_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.banco'),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='clabe',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='comidas_facturas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='hora_partida',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='comentario_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='comentario_jefe_inmediato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
