# Generated by Django 5.0 on 2024-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0033_solicitud_viatico_banco_solicitud_viatico_clabe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='transporte',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
