# Generated by Django 5.0 on 2024-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0034_alter_solicitud_viatico_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
