# Generated by Django 5.0.1 on 2025-04-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_historicalproduct_pais_product_pais'),
        ('viaticos', '0036_alter_puntos_intermedios_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='dashboard.product'),
        ),
    ]
