# Generated by Django 5.0.1 on 2025-04-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_historicalproduct_pais_product_pais'),
        ('viaticos', '0037_alter_concepto_viatico_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='concepto_viatico',
            name='viatico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='viaticos.solicitud_viatico'),
        ),
    ]
