# Generated by Django 5.0 on 2025-06-23 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_tipo_perfil_finanzas'),
        ('viaticos', '0039_viaticos_factura_estado_sat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='persona_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cierre_Viatico', to='user.profile'),
        ),
    ]
