# Generated by Django 5.0 on 2025-06-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0040_solicitud_viatico_comentario_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='cerrar_sin_pago_completo',
            field=models.BooleanField(default=False),
        ),
    ]
