# Generated by Django 5.0 on 2026-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0041_solicitud_viatico_cerrar_sin_pago_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='tipo',
            field=models.CharField(choices=[('CON_PAGO', 'Con pago'), ('SIN_PAGO', 'Sin pago')], default='CON_PAGO', max_length=15, verbose_name='Tipo de viático'),
        ),
    ]
