# Generated by Django 5.0 on 2026-09-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_contrato_tiene_pozos'),
        ('viaticos', '0042_solicitud_viatico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='pozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos', to='solicitudes.pozo'),
        ),
    ]
