# Generated by Django 4.2.4 on 2023-10-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='folio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='mantenimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
