# Generated by Django 4.2.4 on 2023-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activo_codigo_activo_estatus_activo_folio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='cuenta_contable',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='factura_interna',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
