# Generated by Django 4.2.4 on 2023-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activo_codigo_alter_activo_cuenta_contable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='folio',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='folio',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
