# Generated by Django 4.2.4 on 2023-10-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_historicalorder_folio_alter_order_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='folio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='folio',
            field=models.IntegerField(null=True),
        ),
    ]
