# Generated by Django 4.2.4 on 2023-11-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_historicalorder_folio_alter_order_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='approved_at_time',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_at_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at_time',
        ),
    ]
