# Generated by Django 5.0 on 2024-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_historicalorder_approved_at_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosparasurtir',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='historicalarticulosparasurtir',
            name='created_at_time',
        ),
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
