# Generated by Django 5.0.1 on 2024-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
