# Generated by Django 5.0.1 on 2024-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_historicalproduct_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='nombre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
