# Generated by Django 5.0.1 on 2024-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_historicalproduct_nombre_alter_product_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='eco_unidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
