# Generated by Django 5.0 on 2024-03-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_activo_eco_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='cantidad_apartada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_apartada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
