# Generated by Django 5.0 on 2024-04-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_historicalinventario_cantidad_apartada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
