# Generated by Django 5.0 on 2024-04-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_estatus_activo_alter_activo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.estatus_activo'),
        ),
    ]
