# Generated by Django 5.0 on 2024-04-04 15:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_activo_estatus'),
        ('user', '0004_tipo_perfil_activos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='modified_at',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='HistoricalActivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('folio', models.CharField(max_length=50, null=True)),
                ('eco_unidad', models.CharField(max_length=50, null=True)),
                ('serie', models.CharField(max_length=30, null=True)),
                ('cuenta_contable', models.CharField(max_length=25, null=True)),
                ('factura_interna', models.CharField(max_length=15, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('mantenimiento', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('modified_at', models.DateField(null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.inventario')),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('estatus', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.estatus_activo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.marca')),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('tipo_activo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.tipo_activo')),
            ],
            options={
                'verbose_name': 'historical activo',
                'verbose_name_plural': 'historical activos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
