# Generated by Django 5.0 on 2024-04-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_activo_modified_at_historicalactivo'),
        ('user', '0004_tipo_perfil_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
    ]
