# Generated by Django 5.0 on 2024-04-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_activo_modified_by_historicalactivo_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.marca'),
        ),
    ]
