# Generated by Django 5.0 on 2024-04-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_activo_documento_baja_activo_factura_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.activo'),
        ),
    ]
