# Generated by Django 5.0 on 2024-06-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_order_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosordenados',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='dashboard.order'),
        ),
    ]
