# Generated by Django 5.0 on 2024-07-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_articulosordenados_orden'),
        ('solicitudes', '0005_alter_proyecto_cuenta_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.sector'),
        ),
    ]
