# Generated by Django 5.0.1 on 2024-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_order_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='fecha_asignacion',
            field=models.DateField(null=True),
        ),
    ]
