# Generated by Django 5.0.1 on 2024-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_articulosparasurtir_procesado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
