# Generated by Django 5.0 on 2024-09-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_articulosparasurtir_procesado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='comentario',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='comentario',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
