# Generated by Django 5.0.1 on 2024-09-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_activo_fecha_asignacion_and_more'),
        ('dashboard', '0027_alter_historicalorder_comentario_and_more'),
    ]

    operations = [
    ]
