# Generated by Django 5.0.1 on 2024-09-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_merge_20240924_0957'),
        ('dashboard', '0028_merge_20240924_0959'),
    ]

    operations = [
    ]
