# Generated by Django 5.0 on 2024-10-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_merge_20240927_1459'),
        ('dashboard', '0029_merge_20240930_0958'),
    ]

    operations = [
    ]
