# Generated by Django 5.0 on 2024-10-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_merge_20241014_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='last_folio_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_folio_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
