# Generated by Django 5.0 on 2024-11-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_requerimiento_calidad_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='product',
            name='especialista',
        ),
    ]
