# Generated by Django 5.0 on 2024-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_historicalproduct_especialista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='inicio_form',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inicio_form',
            field=models.DateTimeField(null=True),
        ),
    ]
