# Generated by Django 5.0.1 on 2025-01-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_historicalorder_inicio_form_order_inicio_form'),
        ('user', '0011_customuser_apoyo_mantto_customuser_apoyo_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='seleccionado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seleccionado_por', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalarticulosparasurtir',
            name='seleccionado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
    ]
