# Generated by Django 5.0 on 2025-01-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_articulosparasurtir_seleccionado_por_and_more'),
        ('user', '0011_customuser_apoyo_mantto_customuser_apoyo_renta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='seleccionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seleccionado_por', to='user.profile'),
        ),
    ]
