# Generated by Django 5.0.1 on 2025-02-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_articulosparasurtir_seleccionado_por'),
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='pais',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.pais'),
        ),
        migrations.AddField(
            model_name='product',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.pais'),
        ),
    ]
