# Generated by Django 5.0 on 2025-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_historicalproduct_pais_product_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosordenados',
            name='comentario',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
