# Generated by Django 5.0 on 2025-10-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_articulosordenados_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento_calidad',
            name='url',
        ),
    ]
