# Generated by Django 5.0 on 2025-10-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_requerimiento_calidad_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='requerimiento_calidad',
            old_name='nombre',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='requerimiento_calidad',
            name='requerimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tipo_requerimiento'),
        ),
    ]
