# Generated by Django 5.0 on 2025-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_tipo_requerimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento_calidad',
            name='comentarios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
