# Generated by Django 5.0 on 2025-10-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_requerimiento_calidad_comentarios'),
    ]

    operations = [
    ]
