# Generated by Django 5.0 on 2025-10-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_duplicated_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento_calidad',
            name='comentarios',
        ),
    ]
