# Generated by Django 5.0 on 2025-10-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_requerimiento_calidad_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento_calidad',
            name='comentarios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
