# Generated by Django 5.0 on 2025-10-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_requerimiento_calidad_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto_calidad',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='producto_calidad',
            name='requisitos',
        ),
    ]
