# Generated by Django 5.0 on 2025-10-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_remove_historicalproducto_calidad_requisitos_and_more'),
        ('user', '0026_tipo_perfil_cuentas_por_pagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRefChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('autorizado', models.BooleanField(blank=True, null=True)),
                ('solicitado_en', models.DateTimeField(null=True)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_precioref', to='user.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='dashboard.product')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_precioref', to='user.profile')),
            ],
            options={
                'ordering': ['-solicitado_en'],
            },
        ),
    ]
