# Generated by Django 5.0 on 2025-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_pricerefchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerefchange',
            name='new_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
