# Generated by Django 5.0 on 2025-12-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_pricerefchange_new_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricerefchange',
            name='new_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
