# Generated by Django 5.0 on 2026-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_historicalproduct_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='sector_texto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='order',
            name='sector_texto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sector'),
        ),
    ]
