# Generated by Django 5.0 on 2026-08-14 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_historicalorder_sector_texto_order_sector_texto'),
        ('solicitudes', '0014_contrato_tiene_pozos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='pozo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.pozo'),
        ),
        migrations.AddField(
            model_name='order',
            name='pozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='solicitudes.pozo'),
        ),
    ]
