# Generated by Django 5.0 on 2026-09-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_categoria_activo_options'),
        ('dashboard', '0051_historicalorder_pozo_order_pozo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoria_activo'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='activos.categoria_activo'),
        ),
    ]
