# Generated by Django 5.0 on 2026-09-17 20:14

from django.db import migrations

CLASIFICACION = {
    'UBM': [
        1, 3, 15, 16, 17, 21, 22, 30, 42, 45, 47,
    ],
    'VEHICULO': [
        6, 7, 9, 10, 12, 13, 14, 27, 28, 29, 31, 55,
    ],
    'COMPUTO': [
        23, 35, 38, 39, 50, 54, 56, 57,
        58, 63, 64, 65, 66, 68, 70, 72,
    ],
    'CELULAR': [
        36, 37, 49,
    ],
    'EPP': [
        32, 69, 73,
    ],
    'MAQUINARIA Y HERRAMIENTA': [
        5, 8, 24, 26, 34, 46, 51, 71,
    ],
    'OTRO': [
        2, 4, 11, 18, 19, 20, 25, 33, 40, 41,
        43, 44, 48, 52, 53, 59, 60, 61, 62, 67, 74,
    ],
}


def clasificar_activos(apps, schema_editor):
    Activo = apps.get_model('dashboard', 'Activo')
    CategoriaActivo = apps.get_model('activos', 'Categoria_Activo')

    categorias = {
        categoria.nombre: categoria
        for categoria in CategoriaActivo.objects.all()
    }

    faltantes = set(CLASIFICACION) - set(categorias)

    if faltantes:
        raise RuntimeError(
            'No existen estas categorias: '
            + ', '.join(sorted(faltantes))
        )

    for nombre_categoria, tipos_ids in CLASIFICACION.items():
        Activo.objects.filter(
            tipo_activo_id__in=tipos_ids,
        ).update(
            categoria_id=categorias[nombre_categoria].pk,
        )


def revertir_clasificacion(apps, schema_editor):
    Activo = apps.get_model('dashboard', 'Activo')

    for nombre_categoria, tipos_ids in CLASIFICACION.items():
        Activo.objects.filter(
            tipo_activo_id__in=tipos_ids,
            categoria__nombre=nombre_categoria,
        ).update(
            categoria_id=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_cargar_categorias_activo'),
        ('dashboard', '0052_activo_categoria_historicalactivo_categoria'),
    ]

    operations = [
        migrations.RunPython(
            clasificar_activos,
            revertir_clasificacion,
        ),
    ]
