# Generated by Django 5.0 on 2026-09-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0093_invitacionproveedor_distrito'),
        ('dashboard', '0053_clasificar_categorias_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='origen',
            field=models.CharField(blank=True, choices=[('PROPIO', 'Propio'), ('RENTADO', 'Rentado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='precio_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor_adquisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_adquiridos', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='origen',
            field=models.CharField(blank=True, choices=[('PROPIO', 'Propio'), ('RENTADO', 'Rentado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='precio_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='proveedor_adquisicion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.proveedor'),
        ),
    ]
