# Generated by Django 5.0 on 2026-09-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_activo_origen_activo_precio_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
