# Generated by Django 5.0 on 2026-09-19 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0093_invitacionproveedor_distrito'),
        ('dashboard', '0055_activo_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='proveedor_adquisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_adquiridos', to='compras.proveedor_direcciones'),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='proveedor_adquisicion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.proveedor_direcciones'),
        ),
    ]
