# Generated by Django 5.0 on 2026-09-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_activo_proveedor_adquisicion_and_more'),
        ('entradas', '0008_alter_no_conformidad_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='entrada_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_generados', to='entradas.entradaarticulo', verbose_name='Partida de Entrada'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='entrada_articulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.entradaarticulo', verbose_name='Partida de Entrada'),
        ),
    ]
