# Generated by Django 4.2.4 on 2023-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequis',
            name='folio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requis',
            name='folio',
            field=models.IntegerField(null=True),
        ),
    ]
