# Generated by Django 5.0 on 2024-01-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0002_alter_historicalrequis_folio_alter_requis_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valesalidas',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
