# Generated by Django 5.0 on 2024-01-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0003_alter_valesalidas_comentario'),
        ('user', '0003_profile_st_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
    ]
