# Generated by Django 5.0 on 2024-01-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0004_alter_requis_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
    ]
