# Generated by Django 5.0 on 2024-03-15 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_activo_eco_unidad'),
        ('requisiciones', '0004_alter_requis_rejected_by'),
        ('user', '0003_profile_st_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador_requi', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='requis',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requis', to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='requis',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechazo_compras', to='user.profile'),
        ),
    ]
