# Generated by Django 4.2.9 on 2024-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0004_alter_requis_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='valesalidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
    ]
