# Generated by Django 4.2.9 on 2024-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0005_valesalidas_cancelada_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valesalidas',
            name='cancelada_at',
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cancelada_at',
            field=models.DateTimeField(null=True),
        ),
    ]
