# Generated by Django 5.0 on 2024-04-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0006_alter_valesalidas_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosrequisitados',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='requisiciones.requis'),
        ),
    ]
