# Generated by Django 5.0 on 2024-05-03 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0007_alter_articulosrequisitados_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valesalidas',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
