# Generated by Django 5.0 on 2025-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0008_alter_valesalidas_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalidas',
            name='cancelada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='cancelada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
