# Generated by Django 5.0 on 2025-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0009_alter_historicalsalidas_cancelada_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequis',
            name='comentario_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrequis',
            name='devuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrequis',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requis',
            name='comentario_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requis',
            name='devuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requis',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
