# Generated by Django 5.0 on 2026-10-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_activo_entrada_articulo_and_more'),
        ('requisiciones', '0010_historicalrequis_comentario_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valesalidas',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.activo'),
        ),
    ]
