# Generated by Django 4.2.4 on 2023-10-19 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaticos', '0001_initial'),
        ('compras', '0001_initial'),
        ('user', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=16, null=True)),
                ('clabe', models.CharField(max_length=22, null=True)),
                ('monto_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.banco')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveIntegerField(null=True)),
                ('monto', models.DecimalField(decimal_places=4, default=0, max_digits=14, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('pagado_date', models.DateTimeField(blank=True, null=True)),
                ('pagado_real', models.DateField(blank=True, null=True)),
                ('hecho', models.BooleanField(null=True)),
                ('tipo_de_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('comprobante_pago', models.FileField(null=True, upload_to='comprobante', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.cuenta')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto')),
                ('oc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('tesorero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tesorero', to='user.profile')),
                ('viatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.solicitud_viatico')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(blank=True, null=True)),
                ('hora_subido', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compra', to='compras.compra')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='user.profile')),
            ],
        ),
    ]
