# Generated by Django 5.0 on 2024-03-16 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_compra_req_alter_compra_tesorero'),
        ('tesoreria', '0002_alter_facturas_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compra'),
        ),
    ]
