# Generated by Django 5.0 on 2024-04-10 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_alter_compra_tesorero'),
        ('tesoreria', '0003_alter_pago_oc'),
        ('user', '0004_tipo_perfil_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante_saldo_favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(blank=True, null=True)),
                ('hora_subido', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='saldo_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('comprobante_xml', models.FileField(blank=True, null=True, upload_to='saldo_xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
