# Generated by Django 5.0.1 on 2024-05-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0020_alter_articulo_gasto_gasto'),
        ('tesoreria', '0004_comprobante_saldo_favor'),
        ('viaticos', '0025_alter_concepto_viatico_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosg', to='gastos.solicitud_gasto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='viatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosv', to='viaticos.solicitud_viatico'),
        ),
    ]
