# Generated by Django 5.0.1 on 2024-05-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_alter_pago_gasto_alter_pago_viatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
