# Generated by Django 5.0.1 on 2024-05-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_pago_pagado_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.tipo_pago'),
        ),
    ]
