# Generated by Django 5.0.1 on 2024-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_historicalsaldo_cuenta_saldo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaldo_cuenta',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saldo_cuenta',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
