# Generated by Django 5.0.1 on 2024-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_historicalsaldo_cuenta_hecho_saldo_cuenta_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaldo_cuenta',
            name='fecha_inicial',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='saldo_cuenta',
            name='fecha_inicial',
            field=models.DateField(null=True),
        ),
    ]
