# Generated by Django 5.0 on 2024-07-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_historicalproveedor_direcciones_moneda_and_more'),
        ('tesoreria', '0012_cuenta_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='compras.compra'),
        ),
    ]
