# Generated by Django 5.0.1 on 2024-07-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0013_alter_facturas_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='saldo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, null=True),
        ),
    ]
