# Generated by Django 5.0.1 on 2024-07-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0014_pago_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='indice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
