# Generated by Django 5.0.1 on 2024-09-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0015_pago_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
