# Generated by Django 5.0 on 2024-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0016_facturas_fecha_timbrado_facturas_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
