# Generated by Django 5.0.1 on 2025-02-28 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0018_facturas_autorizada_facturas_autorizada_el_and_more'),
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(blank=True, null=True)),
                ('hora_subido', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('complemento_pdf', models.FileField(blank=True, null=True, upload_to='complementos_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cmplemento_xml', models.FileField(blank=True, null=True, upload_to='complementos_xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('validado', models.BooleanField(default=None, null=True)),
                ('validado_fecha', models.DateTimeField(null=True)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complemento', to='tesoreria.facturas')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complemento_subido_por', to='user.profile')),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validado_complemento', to='user.profile')),
            ],
        ),
    ]
