# Generated by Django 5.0.1 on 2025-03-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0019_complemento_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complemento_pago',
            old_name='cmplemento_xml',
            new_name='complemento_xml',
        ),
    ]
