# Generated by Django 5.0.1 on 2025-03-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0020_rename_cmplemento_xml_complemento_pago_complemento_xml'),
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tesorero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pago', to='user.profile'),
        ),
    ]
