# Generated by Django 5.0.1 on 2025-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0021_alter_pago_tesorero'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='estado_sat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fecha_validacion_sat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
