# Generated by Django 5.0 on 2025-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0022_facturas_estado_sat_facturas_fecha_validacion_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='complemento_pago',
            name='facturas',
            field=models.ManyToManyField(blank=True, related_name='complementos', to='tesoreria.facturas'),
        ),
    ]
