# Generated by Django 5.0 on 2025-05-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0023_complemento_pago_facturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complemento_pago',
            name='factura',
        ),
    ]
