# Generated by Django 5.0 on 2025-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0024_remove_complemento_pago_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='control_documentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_control_documentos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
