# Generated by Django 5.0 on 2025-08-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_alter_linea_exhibit_tipo_proveedor'),
        ('tesoreria', '0025_pago_control_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.exhibit'),
        ),
    ]
