# Generated by Django 5.0 on 2025-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0026_pago_exhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='empresa_beneficiario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
