# Generated by Django 5.0 on 2025-09-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0027_pago_empresa_beneficiario'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
    ]
