# Generated by Django 5.0 on 2026-01-26 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0028_pago_distrito'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estado_cuenta_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.cuenta')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta_subido_por', to='user.profile')),
            ],
        ),
    ]
