# Generated by Django 5.0 on 2026-01-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0029_estadocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='periodo',
            field=models.DateField(null=True),
        ),
    ]
