# Generated by Django 5.0 on 2026-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0030_estadocuenta_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
