# Generated by Django 5.0 on 2026-03-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0031_pago_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SIMPLIFICADO', 'Simplificado'), ('MENSUAL', 'Mensual')], default='SIMPLIFICADO', max_length=20),
        ),
    ]
