# Generated by Django 5.0 on 2026-03-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0032_estadocuenta_tipo'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estadocuenta',
            constraint=models.UniqueConstraint(fields=('cuenta', 'periodo', 'tipo'), name='uq_estado_cuenta_cuenta_periodo_tipo'),
        ),
    ]
