# Generated by Django 5.0 on 2026-03-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0033_estadocuenta_uq_estado_cuenta_cuenta_periodo_tipo'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='visor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_visor', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_encargado', to='user.profile'),
        ),
    ]
