# Generated by Django 5.0 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0034_cuenta_visor_alter_cuenta_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_spei_devuelto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='spei_devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
