# Generated by Django 5.0 on 2026-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0035_pago_fecha_spei_devuelto_pago_spei_devuelto'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='visores',
            field=models.ManyToManyField(blank=True, related_name='cuentas_como_visor', to='user.profile'),
        ),
    ]
