# Generated by Django 4.2.4 on 2023-10-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveIntegerField(null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('entrada_date', models.DateTimeField(blank=True, null=True)),
                ('completo', models.BooleanField()),
                ('almacenista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_por_surtir', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agotado', models.BooleanField(default=False)),
                ('liberado', models.BooleanField(default=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('articulo_comprado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.articulocomprado')),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comentarios', models.TextField(blank=True, max_length=200, null=True)),
                ('reporte_date', models.DateField(blank=True, null=True)),
                ('reporte_hora', models.TimeField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=None, null=True)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.entradaarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='No_Conformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=250, null=True)),
                ('nc_date', models.DateField(blank=True, null=True)),
                ('nc_hora', models.TimeField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('almacenista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='NC_Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articulo_comprado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.articulocomprado')),
                ('nc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.no_conformidad')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNo_Conformidad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comentario', models.TextField(max_length=250, null=True)),
                ('nc_date', models.DateField(blank=True, null=True)),
                ('nc_hora', models.TimeField(blank=True, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('completo', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacenista', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.compra')),
            ],
            options={
                'verbose_name': 'historical no_ conformidad',
                'verbose_name_plural': 'historical no_ conformidads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNC_Articulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('history_change_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('articulo_comprado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.articulocomprado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.no_conformidad')),
            ],
            options={
                'verbose_name': 'historical n c_ articulo',
                'verbose_name_plural': 'historical n c_ articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEntradaArticulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_por_surtir', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('agotado', models.BooleanField(default=False)),
                ('liberado', models.BooleanField(default=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('articulo_comprado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.articulocomprado')),
                ('entrada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.entrada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical entrada articulo',
                'verbose_name_plural': 'historical entrada articulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEntrada',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('folio', models.PositiveIntegerField(null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('entrada_date', models.DateTimeField(blank=True, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('completo', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacenista', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.compra')),
            ],
            options={
                'verbose_name': 'historical entrada',
                'verbose_name_plural': 'historical entradas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
