# Generated by Django 4.2.8 on 2023-12-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Nc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='tipo_nc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.tipo_nc'),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='tipo_nc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.tipo_nc'),
        ),
    ]
