# Generated by Django 4.2.8 on 2023-12-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_tipo_nc_historicalno_conformidad_tipo_nc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_nc',
            name='nombre',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
