# Generated by Django 5.0 on 2024-03-16 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_compra_req_alter_compra_tesorero'),
        ('entradas', '0003_alter_tipo_nc_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_entrada', to='compras.compra'),
        ),
    ]
