# Generated by Django 4.2.9 on 2024-01-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_alter_tipo_nc_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
