# Generated by Django 5.0.1 on 2024-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_alter_entrada_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte_calidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calidad'),
        ),
    ]
