# Generated by Django 5.0.1 on 2024-05-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_reporte_calidad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre_Nc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calidad'),
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='cierre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.cierre_nc'),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.cierre_nc'),
        ),
    ]
