# Generated by Django 5.0 on 2025-07-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0061_compra_comentario_cierre_and_more'),
        ('entradas', '0007_entrada_cancelada_historicalentrada_cancelada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_conformidad',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidad', to='compras.compra'),
        ),
    ]
