# Generated by Django 5.0 on 2026-08-20 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='UUID')),
                ('version_cfdi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Versión CFDI')),
                ('tipo_comprobante', models.CharField(blank=True, choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago'), ('N', 'Nómina'), ('T', 'Traslado')], max_length=1, null=True, verbose_name='Tipo de comprobante')),
                ('serie', models.CharField(blank=True, max_length=30, null=True)),
                ('folio', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rfc_emisor', models.CharField(db_index=True, max_length=13)),
                ('nombre_emisor', models.CharField(blank=True, max_length=300, null=True)),
                ('regimen_fiscal_emisor', models.CharField(blank=True, max_length=10, null=True)),
                ('rfc_receptor', models.CharField(db_index=True, max_length=13)),
                ('nombre_receptor', models.CharField(blank=True, max_length=300, null=True)),
                ('regimen_fiscal_receptor', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_fiscal_receptor', models.CharField(blank=True, max_length=10, null=True)),
                ('uso_cfdi', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=18)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=10, null=True)),
                ('archivo_xml', models.FileField(upload_to='boveda_xml/xml/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de vincular'), ('VINCULADO', 'Vinculado'), ('CANCELADO', 'Cancelado en SAT')], db_index=True, default='PENDIENTE', max_length=20)),
                ('estado_sat', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_validacion_sat', models.DateTimeField(blank=True, null=True)),
                ('fecha_subido', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfdi_boveda_subidos', to='user.profile')),
            ],
            options={
                'verbose_name': 'CFDI',
                'verbose_name_plural': 'CFDI',
                'ordering': ['-fecha_timbrado', '-fecha_subido'],
                'indexes': [models.Index(fields=['rfc_emisor', 'fecha_timbrado'], name='cfdi_emisor_fecha_idx'), models.Index(fields=['rfc_receptor', 'fecha_timbrado'], name='cfdi_receptor_fecha_idx')],
            },
        ),
    ]
