# Generated by Django 5.0.1 on 2024-02-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subproyecto',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
