# Generated by Django 5.0 on 2024-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_subproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='eco_unidad',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
