# Generated by Django 5.0 on 2024-03-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_activo_eco_unidad'),
        ('solicitudes', '0003_alter_subproyecto_descripcion'),
    ]

    operations = [
    ]
