# Generated by Django 5.0 on 2024-04-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_merge_20240311_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.cuenta_contable'),
        ),
    ]
