# Generated by Django 5.0 on 2025-09-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_contrato_proyecto_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='status_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.status_contrato'),
        ),
    ]
