# Generated by Django 5.0 on 2025-09-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_status_contrato_contrato_status_contrato'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='user.profile'),
        ),
    ]
