# Generated by Django 5.0 on 2026-04-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_contrato_complete_contrato_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Costo_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
