# Generated by Django 5.0 on 2026-04-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_clase_costo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.clase_costo_proyecto'),
        ),
    ]
