# Generated by Django 5.0 on 2026-07-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_proyecto_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoSubproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Guardar el primer día del mes, por ejemplo: 2026-07-01')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='solicitudes.subproyecto')),
            ],
            options={
                'ordering': ['periodo'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodosubproyecto',
            constraint=models.UniqueConstraint(fields=('subproyecto', 'periodo'), name='periodo_unico_por_subproyecto'),
        ),
    ]
