# Generated by Django 5.0 on 2026-08-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_periodosubproyecto_and_more'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cerrar_pozo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozos', to='solicitudes.contrato')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozos', to='user.distrito')),
            ],
            options={
                'verbose_name': 'Pozo',
                'verbose_name_plural': 'Pozos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='pozo',
            constraint=models.UniqueConstraint(fields=('contrato', 'nombre'), name='pozo_unico_por_contrato'),
        ),
    ]
