# Generated by Django 5.0 on 2026-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_pozo_pozo_pozo_unico_por_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='cerrar_pozo',
            field=models.BooleanField(default=False),
        ),
    ]
