# Generated by Django 5.0 on 2026-08-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_pozo_cerrar_pozo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tiene_pozos',
            field=models.BooleanField(default=False, verbose_name='¿El contrato maneja pozos?'),
        ),
    ]
