# Generated by Django 5.0 on 2024-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='gerente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
