# Generated by Django 5.0 on 2024-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_st_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='activos',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
