# Generated by Django 5.0 on 2024-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tipo_perfil_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='dg',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
