# Generated by Django 5.0 on 2024-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tipo_perfil_dg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='subdirector',
            field=models.BooleanField(default=False),
        ),
    ]
