# Generated by Django 5.0 on 2024-06-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tipo_perfil_subdirector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nivel',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
