# Generated by Django 5.0 on 2024-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='rh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_perfil',
            name='dg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_perfil',
            name='oc_gerencia',
            field=models.BooleanField(default=False),
        ),
    ]
