# Generated by Django 5.0.1 on 2024-06-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_tipo_perfil_rh_alter_tipo_perfil_dg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sustituto_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustitutos', to='user.customuser'),
        ),
    ]
