# Generated by Django 5.0.1 on 2024-06-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_sustituto_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sustituto_de',
            new_name='sustituto',
        ),
    ]
