# Generated by Django 5.0.1 on 2024-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apoyo_mantto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='apoyo_renta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
