# Generated by Django 5.0.1 on 2025-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_apoyo_mantto_customuser_apoyo_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='provevedor_externo',
            field=models.BooleanField(default=False),
        ),
    ]
