# Generated by Django 5.0.1 on 2025-01-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_tipo_perfil_provevedor_externo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_perfil',
            old_name='provevedor_externo',
            new_name='proveedor_externo',
        ),
    ]
