# Generated by Django 5.0.1 on 2025-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='bic',
            field=models.CharField(blank=True, help_text='Código BIC de 8 u 11 caracteres', max_length=11, null=True),
        ),
    ]
