# Generated by Django 5.0.1 on 2025-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_banco_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
