# Generated by Django 5.0.1 on 2025-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_empresa_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='proyectos',
            field=models.BooleanField(default=False),
        ),
    ]
