# Generated by Django 5.0.1 on 2025-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_tipo_perfil_productos_tipo_perfil_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='documentos',
            field=models.BooleanField(default=False),
        ),
    ]
