# Generated by Django 5.0.1 on 2025-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_tipo_perfil_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='pagos',
            field=models.BooleanField(default=False),
        ),
    ]
