# Generated by Django 5.0.1 on 2025-04-14 16:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tipo_perfil_pagos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=25, null=True)),
                ('clabe', models.CharField(blank=True, max_length=22, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('puesto', models.CharField(blank=True, max_length=40, null=True)),
                ('apoyo_renta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('apoyo_mantto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.banco')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical custom user',
                'verbose_name_plural': 'historical custom users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
