# Generated by Django 5.0.1 on 2025-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_historicalcustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='proveedores_edicion',
            field=models.BooleanField(default=False),
        ),
    ]
