# Generated by Django 5.0.1 on 2025-04-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0052_remove_historicalproveedor_perfil_proveedor_and_more'),
        ('user', '0021_tipo_perfil_proveedores_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='compras.proveedor'),
        ),
    ]
