# Generated by Django 5.0 on 2025-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profile_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='para_pago',
            field=models.BooleanField(default=False),
        ),
    ]
