# Generated by Django 5.0 on 2025-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_tipo_perfil_para_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='finanzas',
            field=models.BooleanField(default=False),
        ),
    ]
