# Generated by Django 5.0 on 2025-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='rentabilidad',
            field=models.BooleanField(default=False),
        ),
    ]
