# Generated by Django 5.0 on 2025-10-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_tipo_perfil_rentabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='cuentas_por_pagar',
            field=models.BooleanField(default=False),
        ),
    ]
