# Generated by Django 5.0 on 2026-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_tipo_perfil_cuentas_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
