# Generated by Django 5.0 on 2026-09-18 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='distrito',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
