# Generated by Django 5.0 on 2026-09-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Activo',
            new_name='Categoria_Activo',
        ),
    ]
