# Generated by Django 5.0 on 2026-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_rename_tipo_activo_categoria_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_activo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de activo', 'verbose_name_plural': 'Categorías de activos'},
        ),
        migrations.AlterField(
            model_name='categoria_activo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
