# Generated by Django 5.0 on 2026-09-17 18:56

from django.db import migrations

CATEGORIAS = [
    'UBM',
    'VEHICULO',
    'COMPUTO',
    'CELULAR',
    'EPP',
    'MAQUINARIA Y HERRAMIENTA',
    'OTRO',
]


def cargar_categorias(apps, schema_editor):
    CategoriaActivo = apps.get_model(
        'activos',
        'Categoria_Activo',
    )

    for nombre in CATEGORIAS:
        CategoriaActivo.objects.get_or_create(nombre=nombre)


def eliminar_categorias(apps, schema_editor):
    CategoriaActivo = apps.get_model(
        'activos',
        'Categoria_Activo',
    )

    CategoriaActivo.objects.filter(
        nombre__in=CATEGORIAS,
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_categoria_activo_options_and_more'),
    ]

    operations = [
         migrations.RunPython(
            cargar_categorias,
            eliminar_categorias,
        ),
    ]
