# Generated by Django 5.0 on 2026-09-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_cargar_categorias_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_activo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria de activo', 'verbose_name_plural': 'Categorias de activos'},
        ),
    ]
