# Generated by Django 5.0 on 2026-09-21 20:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_categoria_activo_options'),
        ('dashboard', '0056_alter_activo_proveedor_adquisicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('MOTOCICLETA', 'Motocicleta'), ('MOTOCARRO', 'Motocarro'), ('AUTOMOVIL', 'Automóvil'), ('SUV', 'SUV'), ('VAN', 'Van'), ('PICK UP', 'Pick up'), ('TRACTOCAMION', 'Tractocamión'), ('REMOLQUE CUELLO DE GANZO', 'Remolque cuello de ganso'), ('REMOLQUE', 'Remolque'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión')], max_length=30, null=True)),
                ('anio_modelo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año modelo')),
                ('numero_motor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de motor')),
                ('color', models.CharField(blank=True, choices=[('AZUL', 'Azul'), ('BLANCO', 'Blanco'), ('BLANCO CANDY', 'Blanco candy'), ('GRIS', 'Gris'), ('GRIS/PLATA', 'Gris/Plata'), ('NEGRO', 'Negro'), ('ROJO', 'Rojo')], max_length=20, null=True)),
                ('placas', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('estado_registro', models.CharField(blank=True, choices=[('FEDERAL', 'Federal'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('VERACRUZ', 'Veracruz')], max_length=20, null=True, verbose_name='Estado de registro')),
                ('vigencia_poliza', models.DateField(blank=True, null=True, verbose_name='Vigencia de póliza')),
                ('numero_poliza', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de póliza')),
                ('cobertura', models.CharField(blank=True, choices=[('AMPLIA', 'Amplia'), ('LIMITADA', 'Limitada'), ('0017', '0017')], max_length=15, null=True)),
                ('fecha_verificacion', models.DateField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='dashboard.activo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['activo__eco_unidad'],
            },
        ),
    ]
