# Generated by Django 5.0 on 2026-09-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_vehiculo_activo'),
        ('dashboard', '0056_alter_activo_proveedor_adquisicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBM_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubm', models.CharField(blank=True, choices=[('UBM_120', 'UBM 120"'), ('UBM_144', 'UBM / UBMC 144"'), ('UBMSC_300', 'UBMSC 300"'), ('UBMSC_320', 'UBMSC 320"'), ('UBMSC_360', 'UBMSC 360"')], max_length=20, null=True)),
                ('serie_acumulador', models.CharField(blank=True, max_length=30, null=True)),
                ('serie_cilindro', models.CharField(blank=True, max_length=30, null=True)),
                ('deposito_aceite', models.CharField(blank=True, max_length=30, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('pedestal', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubm', to='dashboard.activo')),
            ],
        ),
    ]
