# Generated by Django 5.0 on 2026-09-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_ubm_activo'),
        ('solicitudes', '0014_contrato_tiene_pozos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba_UBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=30, null=True)),
                ('marca', models.CharField(blank=True, choices=[('DANFOSS', 'Danfoss'), ('KAWASAKI', 'Kawasaki'), ('KPM', 'KPM'), ('OTRA', 'Otra'), ('NO_APLICA', 'No aplica')], max_length=20, null=True)),
                ('numero_interno', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manifold_UBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=30, null=True)),
                ('marca', models.CharField(blank=True, choices=[('VORDCAB', 'Vordcab'), ('OTRO', 'Otro')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motor_UBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('V6_43', 'CI V6 4.3 L'), ('V6_44', 'CI V6 4.4 L'), ('V6_45', 'CI V6 4.5 L'), ('V6_48', 'CI V6 4.8 L'), ('V8_57', 'CI V8 5.7 L')], max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=30, null=True)),
                ('factura', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ubm_activo',
            name='pozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubms', to='solicitudes.pozo'),
        ),
        migrations.AddField(
            model_name='ubm_activo',
            name='bomba',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubm_actual', to='activos.bomba_ubm'),
        ),
        migrations.AddField(
            model_name='ubm_activo',
            name='manifold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubm_actual', to='activos.manifold_ubm'),
        ),
        migrations.AddField(
            model_name='ubm_activo',
            name='motor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubm_actual', to='activos.motor_ubm'),
        ),
    ]
