# Generated by Django 5.0 on 2026-09-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_bomba_ubm_manifold_ubm_motor_ubm_ubm_activo_pozo_and_more'),
        ('dashboard', '0057_activo_entrada_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor_ubm',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='motor_ubm',
            name='serie',
        ),
        migrations.AddField(
            model_name='motor_ubm',
            name='activo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='dashboard.activo'),
        ),
    ]
