# Generated by Django 5.0 on 2026-09-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_remove_motor_ubm_factura_remove_motor_ubm_serie_and_more'),
        ('dashboard', '0057_activo_entrada_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_ubm',
            name='activo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='dashboard.activo'),
        ),
    ]
