# Generated by Django 5.0 on 2026-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_alter_motor_ubm_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubm_activo',
            name='bomba',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubm_activo',
            name='manifold',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
