# Generated by Django 5.0 on 2026-10-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_alter_ubm_activo_bomba_alter_ubm_activo_manifold'),
        ('dashboard', '0057_activo_entrada_articulo_and_more'),
        ('user', '0028_distrito_latitud_distrito_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('DESASIGNACION', 'Desasignación')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='dashboard.activo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_responsable_activos', to='user.profile')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignacion_anterior', to='user.profile')),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignacion_nueva', to='user.profile')),
            ],
            options={
                'verbose_name': 'Historial de asignación de activo',
                'verbose_name_plural': 'Historial de asignaciones de activos',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['activo', '-fecha'], name='idx_asig_activo_fecha')],
            },
        ),
    ]
