# Generated by Django 5.0 on 2026-10-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_historialasignacionactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialasignacionactivo',
            name='eco_unidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historialasignacionactivo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación')], max_length=20),
        ),
    ]
