# Generated by Django 4.2.4 on 2023-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='folio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='folio',
            field=models.IntegerField(null=True),
        ),
    ]
