# Generated by Django 4.2.4 on 2023-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_folio_alter_historicalcompra_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
