# Generated by Django 4.2.4 on 2023-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_retencion_historicalcompra_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativo',
            name='cotizacion4',
            field=models.FileField(null=True, upload_to='facturas'),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='cotizacion5',
            field=models.FileField(null=True, upload_to='facturas'),
        ),
    ]
