# Generated by Django 5.0 on 2024-01-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_fecha_pago_historicalcompra_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='comparativo',
            name='proveedor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor2', to='compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='comparativo',
            name='proveedor3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor3', to='compras.proveedor'),
        ),
    ]
