# Generated by Django 5.0 on 2024-01-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_comparativo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativo',
            name='cotizacion4',
            field=models.FileField(blank=True, null=True, upload_to='comparativos'),
        ),
        migrations.AlterField(
            model_name='comparativo',
            name='cotizacion5',
            field=models.FileField(blank=True, null=True, upload_to='comparativos'),
        ),
    ]
