# Generated by Django 5.0 on 2024-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_remove_historicalproveedor_direcciones_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
