# Generated by Django 5.0 on 2024-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_articulocomprado_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='costo_iva',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_oc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_iva',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_oc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
