# Generated by Django 5.0 on 2024-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_compra_costo_iva_alter_compra_costo_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comentario_gerencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='comentario_gerencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
