# Generated by Django 5.0 on 2024-03-15 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_compra_comentario_gerencia_and_more'),
        ('requisiciones', '0004_alter_requis_rejected_by'),
        ('user', '0003_profile_st_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='requisiciones.requis'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tesorero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tesoreria', to='user.profile'),
        ),
    ]
