# Generated by Django 5.0 on 2024-03-20 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_compra_req_alter_compra_tesorero'),
        ('user', '0003_profile_st_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tesorero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tesoreria', to='user.profile'),
        ),
    ]
