# Generated by Django 5.0 on 2024-04-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_alter_compra_tesorero'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comentario_solicitud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='comentario_solicitud',
            field=models.BooleanField(default=False),
        ),
    ]
