# Generated by Django 5.0 on 2024-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_compra_comentario_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='arrendamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='arrendamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='servicio',
            field=models.BooleanField(default=False),
        ),
    ]
