# Generated by Django 5.0.1 on 2024-08-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_historicalproveedor_direcciones_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comentarios',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='comentarios',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
