# Generated by Django 5.0.1 on 2024-08-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_historicalproveedor_direcciones_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='para_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='para_pago',
            field=models.BooleanField(default=False),
        ),
    ]
