# Generated by Django 5.0.1 on 2024-09-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_alter_compra_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='convenio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='convenio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
