# Generated by Django 5.0.1 on 2024-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_compra_para_pago_historicalcompra_para_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
