# Generated by Django 5.0 on 2024-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_historicalproveedor_direcciones_convenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
