# Generated by Django 5.0.1 on 2024-09-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_compra_parcial_historicalcompra_parcial'),
        ('compras', '0022_historicalproveedor_direcciones_convenio_and_more'),
    ]

    operations = [
    ]
