# Generated by Django 5.0 on 2024-09-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_alter_compra_fecha_pago_and_more'),
        ('compras', '0023_merge_20240919_0955'),
    ]

    operations = [
    ]
