# Generated by Django 5.0 on 2024-09-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_merge_20240919_1918'),
        ('compras', '0024_merge_20240920_1030'),
    ]

    operations = [
    ]
