# Generated by Django 5.0 on 2024-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_merge_20240920_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='visita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='visita',
            field=models.BooleanField(default=False),
        ),
    ]
