# Generated by Django 5.0 on 2024-11-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_remove_historicalproveedor_direcciones_visita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_comercial',
        ),
    ]
