# Generated by Django 5.0.1 on 2025-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0028_remove_historicalproveedor_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor_direcciones',
            name='modificado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='modificado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
