# Generated by Django 5.0.1 on 2025-01-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0028_remove_historicalproveedor_nombre_comercial_and_more'),
        ('user', '0011_customuser_apoyo_mantto_customuser_apoyo_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='perfil_proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='perfil_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov_perfil', to='user.profile'),
        ),
    ]
