# Generated by Django 5.0.1 on 2025-01-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_alter_historicalproveedor_direcciones_modificado_fecha_and_more'),
        ('compras', '0029_historicalproveedor_perfil_proveedor_and_more'),
    ]

    operations = [
    ]
