# Generated by Django 5.0.1 on 2025-01-27 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0030_merge_20250127_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='csf',
            field=models.TextField(max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='csf',
            field=models.FileField(null=True, upload_to='csf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
    ]
