# Generated by Django 5.0.1 on 2025-02-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0031_historicalproveedor_csf_proveedor_csf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor',
            name='rfc',
            field=models.CharField(db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
