# Generated by Django 5.0.1 on 2025-02-21 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0033_estado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor',
            name='csf',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='csf',
            field=models.FileField(blank=True, null=True, upload_to='csf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
    ]
