# Generated by Django 5.0.1 on 2025-02-25 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0034_alter_historicalproveedor_csf_alter_proveedor_csf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comprobante_domicilio',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='opinion_cumplimiento',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='comprobante_domicilio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='opinion_cumplimiento',
            field=models.FileField(blank=True, null=True, upload_to='opinion_cumplimiento', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
    ]
