# Generated by Django 5.0.1 on 2025-02-26 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0037_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='file',
            field=models.FileField(upload_to='evidencias', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg'))]),
        ),
    ]
