# Generated by Django 5.0.1 on 2025-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0038_evidencia_hecho_alter_evidencia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
