# Generated by Django 5.0.1 on 2025-02-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0039_evidencia_comentario'),
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='activated',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='uploaded',
            field=models.DateField(),
        ),
    ]
