# Generated by Django 5.0.1 on 2025-03-05 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0040_remove_evidencia_activated_evidencia_subido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='curriculum',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculum', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.CreateModel(
            name='DocumentosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('competencias', 'Competencias'), ('contrato', 'Contrato'), ('factura_predial', 'Factura del Bien/Predial')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_proveedores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='compras.proveedor')),
            ],
        ),
    ]
