# Generated by Django 5.0.1 on 2025-03-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0041_historicalproveedor_curriculum_proveedor_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='comprobante_domicilio',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='credencial_acta_constitutiva',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='csf',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='opinion_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='comprobante_domicilio',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='credencial_acta_constitutiva',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='csf',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='opinion_cumplimiento',
        ),
        migrations.AlterField(
            model_name='documentosproveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('csf', 'CSF'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('opinion_cumplimiento', 'Opinión de Cumplimiento'), ('credencial_acta_constitutiva', 'Credencial/Acta Constitutiva'), ('curriculum', 'Curriculum'), ('competencias', 'Competencias'), ('contrato', 'Contrato'), ('factura_predial', 'Factura del Bien/Predial')], max_length=50),
        ),
    ]
