# Generated by Django 5.0.1 on 2025-03-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0042_remove_historicalproveedor_comprobante_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='compras.proveedor'),
        ),
    ]
