# Generated by Django 5.0.1 on 2025-03-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0043_alter_proveedor_direcciones_nombre'),
        ('user', '0014_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosproveedor',
            name='validada',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='documentosproveedor',
            name='validada_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documentosproveedor',
            name='validada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validada_por', to='user.profile'),
        ),
    ]
