# Generated by Django 5.0.1 on 2025-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_documentosproveedor_validada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosproveedor',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
