# Generated by Django 5.0.1 on 2025-03-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0046_historicalproveedor_comentario_csf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_acta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_competencias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_comprobante_domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_curriculum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_factura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_opinion_cumplimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_acta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_competencias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_comprobante_domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_contrato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_curriculum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_factura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_opinion_cumplimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
