# Generated by Django 5.0.1 on 2025-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0047_historicalproveedor_comentario_acta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosproveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('csf', 'CSF'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('opinion_cumplimiento', 'Opinión de Cumplimiento'), ('credencial_acta_constitutiva', 'Credencial/Acta Constitutiva'), ('curriculum', 'Curriculum'), ('competencias', 'Competencias'), ('contrato', 'Contrato'), ('factura_predial', 'Factura del Bien/Predial'), ('calidad', 'Calidad'), ('otros', 'Otros')], max_length=50),
        ),
    ]
