# Generated by Django 5.0.1 on 2025-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0048_alter_documentosproveedor_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_calidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_otros',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_calidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_otros',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
