# Generated by Django 5.0.1 on 2025-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0049_historicalproveedor_comentario_calidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='acepto_politica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acepto_politica',
            field=models.BooleanField(default=False),
        ),
    ]
