# Generated by Django 5.0 on 2025-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0053_invitacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='acepto_politica_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acepto_politica_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
