# Generated by Django 5.0 on 2025-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0054_historicalproveedor_acepto_politica_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='acepto_aviso_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='acepto_codigo_etica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acepto_aviso_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acepto_codigo_etica',
            field=models.BooleanField(default=False),
        ),
    ]
