# Generated by Django 5.0 on 2025-05-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0055_historicalproveedor_acepto_aviso_privacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
