# Generated by Django 5.0 on 2025-05-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0056_historicalproveedor_folio_consecutivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosproveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('csf', 'CSF'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('opinion_cumplimiento', 'Opinión de Cumplimiento'), ('credencial_acta_constitutiva', 'Credencial/Acta Constitutiva'), ('curriculum', 'Curriculum'), ('competencias', 'Competencias'), ('contrato', 'Contrato'), ('factura_predial', 'Factura del Bien/Predial'), ('calidad', 'Calidad'), ('calificacion', 'Calificación'), ('visita', 'Visita'), ('carta_credito', 'Carta de Crédito'), ('otros', 'Otros')], max_length=50),
        ),
    ]
