# Generated by Django 5.0 on 2025-05-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0057_alter_documentosproveedor_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_calificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_carta_credito',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_visita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_calificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_carta_credito',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_visita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
