# Generated by Django 5.0 on 2025-06-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0058_historicalproveedor_comentario_calificacion_and_more'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cerrar_sin_pago_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='persona_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cierre', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='cerrar_sin_pago_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='persona_cierre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
    ]
