# Generated by Django 5.0 on 2025-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0059_compra_cerrar_sin_pago_completo_compra_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
