# Generated by Django 5.0 on 2025-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0060_alter_compra_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
