# Generated by Django 5.0 on 2025-08-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0061_compra_comentario_cierre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.tipoprioridad'),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='tipo_prioridad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.tipoprioridad'),
        ),
    ]
