# Generated by Django 5.0 on 2025-08-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0062_tipoprioridad_compra_tipo_prioridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debida_Diligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('representante_nombre', models.CharField(max_length=255)),
                ('sitio_web', models.URLField(blank=True)),
                ('empleado_funcionarios_publicos', models.BooleanField()),
                ('pertenece_funcionario_publico', models.BooleanField()),
                ('notificar_relacion_familiar', models.BooleanField()),
                ('cuentas_bloqueadas', models.BooleanField()),
                ('detalle_cuentas_bloqueadas', models.TextField(blank=True)),
                ('financiamiento_externo', models.BooleanField()),
                ('fuentes_financiamiento', models.TextField(blank=True)),
                ('controles_antilavado', models.BooleanField()),
                ('responsables_interactuar', models.BooleanField()),
                ('respeta_derechos_humanos', models.BooleanField()),
                ('elimina_trabajo_forzoso', models.BooleanField()),
                ('empleados_contrato_prestaciones', models.BooleanField()),
                ('explicacion_sin_contrato', models.TextField(blank=True)),
                ('erradica_trabajo_infantil', models.BooleanField()),
                ('elimina_discriminacion', models.BooleanField()),
                ('enfoque_medio_ambiente', models.BooleanField()),
                ('codigo_etica', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('codigo_conducta', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('politica_anticorrupcion', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('otro_documento_etico', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('transparencia_donativos', models.BooleanField()),
                ('conocimiento_publico', models.BooleanField()),
                ('extensivo_grupos_interes', models.BooleanField()),
                ('transparencia_contribuciones_politicas', models.BooleanField()),
                ('prohibicion_sobornos', models.BooleanField()),
                ('prohibicion_incentivos', models.BooleanField()),
                ('prohibicion_lavado_dinero', models.BooleanField()),
                ('manual_organizacion', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('verifica_perfil_etico', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('descripcion_verificacion', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('capacitacion_anticorrupcion', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('medio_denuncia', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('En proceso', 'En proceso')], max_length=20)),
                ('seguimiento_denuncia', models.BooleanField()),
                ('descripcion_seguimiento', models.TextField(blank=True)),
                ('directivos_hablan_de_corrupcion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accionistas', to='compras.debida_diligencia')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario_Publico_Relacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('puesto_gubernamental', models.CharField(max_length=100)),
                ('periodo_funciones', models.CharField(blank=True, max_length=50, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_publicos', to='compras.debida_diligencia')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Alta_Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anios_servicio', models.PositiveIntegerField()),
                ('cargo', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=25, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_direccion', to='compras.debida_diligencia')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Servidor_Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servidor', models.CharField(max_length=50)),
                ('tipos_relacion', models.CharField(max_length=50)),
                ('puesto_ocupado', models.CharField(max_length=100)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_servidores', to='compras.debida_diligencia')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('trabajo_previo_vordcab', models.BooleanField(default=False)),
                ('anio_baja', models.PositiveIntegerField(blank=True, null=True)),
                ('puesto_ocupado', models.CharField(max_length=100)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_interaccion', to='compras.debida_diligencia')),
            ],
        ),
    ]
