# Generated by Django 5.0 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0063_debida_diligencia_accionista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion_servidor_publico',
            name='puesto_ocupado',
        ),
        migrations.AddField(
            model_name='funcionario_publico_relacionado',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='relacion_servidor_publico',
            name='porcentaje_participacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
