# Generated by Django 5.0 on 2025-08-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0064_remove_relacion_servidor_publico_puesto_ocupado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debida_diligencia',
            name='descripcion_verificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='debida_diligencia',
            name='verifica_perfil_etico',
            field=models.BooleanField(),
        ),
    ]
