# Generated by Django 5.0 on 2025-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0066_debida_diligencia_tiene_alta_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debida_diligencia',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
