# Generated by Django 5.0 on 2025-08-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0067_debida_diligencia_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='debida_diligencia',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='compras.proveedor'),
        ),
    ]
