# Generated by Django 5.0 on 2025-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0068_debida_diligencia_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debida_diligencia',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
