# Generated by Django 5.0 on 2025-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0069_alter_debida_diligencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debida_diligencia',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
