# Generated by Django 5.0 on 2025-08-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0070_alter_debida_diligencia_sitio_web'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='debida_diligencia',
            name='elaborado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elaborado_por', to='user.profile'),
        ),
    ]
