# Generated by Django 5.0 on 2025-08-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0071_debida_diligencia_elaborado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debida_diligencia',
            name='elaborado_por',
        ),
    ]
