# Generated by Django 5.0 on 2025-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0072_remove_debida_diligencia_elaborado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
