# Generated by Django 5.0 on 2025-10-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0073_compra_local_historicalcompra_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='local',
            field=models.BooleanField(default=True),
        ),
    ]
