# Generated by Django 5.0 on 2025-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0077_alter_documentosproveedor_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosproveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('csf', 'CSF'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('opinion_cumplimiento', 'Opinión de Cumplimiento'), ('credencial_acta_constitutiva', 'Credencial/Acta Constitutiva'), ('curriculum', 'Curriculum'), ('competencias', 'Competencias'), ('contrato', 'Contrato'), ('factura_predial', 'Factura del Bien/Predial'), ('calidad', 'Calidad'), ('calificacion', 'Calificación'), ('visita', 'Visita'), ('carta_credito', 'Carta de Crédito'), ('cotizacion', 'Cotización'), ('busqueda_mediatica', 'Búsqueda Mediática'), ('cumplimiento_imss', 'Cumplimiento IMSS'), ('repse', 'REPSE'), ('otros', 'Otros')], max_length=50),
        ),
    ]
