# Generated by Django 5.0 on 2025-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0078_alter_documentosproveedor_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_cotizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_cumplimiento_imss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_cotizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_cumplimiento_imss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
