# Generated by Django 5.0 on 2025-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0079_historicalproveedor_comentario_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='comentario_repse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentario_repse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
