# Generated by Django 5.0 on 2025-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0080_historicalproveedor_comentario_repse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionproveedor',
            name='tipo',
            field=models.CharField(choices=[('NUEVO_PROVEEDOR', 'NUEVO_PROVEEDOR'), ('NUEVA_DIRECCION', 'NUEVA_DIRECCION'), ('NUEVO_USUARIO', 'NUEVO_USUARIO')], default='NUEVO_PROVEEDOR', max_length=20),
        ),
    ]
