# Generated by Django 5.0 on 2025-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0081_invitacionproveedor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionproveedor',
            name='arrendamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitacionproveedor',
            name='producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitacionproveedor',
            name='servicio',
            field=models.BooleanField(default=False),
        ),
    ]
