# Generated by Django 5.0 on 2025-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0082_invitacionproveedor_arrendamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosproveedor',
            name='fecha_obsoleto',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='documentosproveedor',
            name='obsoleto',
            field=models.BooleanField(default=False),
        ),
    ]
