# Generated by Django 5.0 on 2025-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0083_documentosproveedor_fecha_obsoleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosproveedor',
            name='fecha_adicional',
            field=models.DateField(blank=True, null=True),
        ),
    ]
