# Generated by Django 5.0 on 2026-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0084_documentosproveedor_fecha_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='comentario_status',
            field=models.CharField(blank=True, help_text='Comentario asociado al estatus del proveedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='comentario_status',
            field=models.CharField(blank=True, help_text='Comentario asociado al estatus del proveedor', max_length=255, null=True),
        ),
    ]
