# Generated by Django 5.0 on 2026-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0085_historicalproveedor_direcciones_comentario_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor_direcciones',
            name='comentario_status',
            field=models.CharField(help_text='Comentario asociado al estatus del proveedor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='comentario_status',
            field=models.CharField(help_text='Comentario asociado al estatus del proveedor', max_length=255, null=True),
        ),
    ]
