# Generated by Django 5.0 on 2026-03-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0086_alter_historicalproveedor_direcciones_comentario_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='tipo_contratacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.tipo_contrato'),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='tipo_contratacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipo_contrato'),
        ),
    ]
