# Generated by Django 5.0 on 2026-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0087_tipo_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_contrato',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
