# Generated by Django 5.0 on 2026-03-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0088_alter_tipo_contrato_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproveedor_direcciones',
            name='tipo_contratacion',
        ),
        migrations.RemoveField(
            model_name='proveedor_direcciones',
            name='tipo_contratacion',
        ),
    ]
