# Generated by Django 5.0 on 2026-03-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0089_remove_historicalproveedor_direcciones_tipo_contratacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_contratacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipo_contrato'),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='tipo_contratacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.tipo_contrato'),
        ),
    ]
