# Generated by Django 5.0 on 2026-03-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0090_compra_tipo_contratacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocomprado',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulocomprado',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
