# Generated by Django 5.0 on 2026-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0091_articulocomprado_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionproveedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
