# Generated by Django 5.0 on 2026-08-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0092_alter_invitacionproveedor_email'),
        ('user', '0027_customuser_extension_historicalcustomuser_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionproveedor',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_proveedor', to='user.distrito'),
        ),
    ]
