# Generated by Django 4.2.4 on 2023-10-19 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('user', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.BooleanField(default=False, null=True)),
                ('comentario', models.CharField(max_length=75, null=True)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('otros_impuestos', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True)),
                ('impuestos_retenidos', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('entrada_salida_express', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('completo', models.BooleanField(default=False)),
                ('validacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=6, null=True, unique=True)),
                ('complete', models.BooleanField(null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('autorizar', models.BooleanField(default=None, null=True)),
                ('autorizar2', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateField(null=True)),
                ('created_at_time', models.TimeField(null=True)),
                ('approved_at', models.DateField(null=True)),
                ('approved_at_time', models.TimeField(null=True)),
                ('approbado_fecha2', models.DateField(null=True)),
                ('approved_at_time2', models.TimeField(null=True)),
                ('facturas_completas', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.operacion')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignado_gasto', to='user.profile')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Crea_gasto', to='user.profile')),
                ('superintendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superintendente', to='user.profile')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.tipo_gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('archivo_xml', models.FileField(upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('solicitud_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gastos.solicitud_gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_Gasto_Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completado_fecha', models.DateField(null=True)),
                ('completado_hora', models.TimeField(null=True)),
                ('completo', models.BooleanField(default=False)),
                ('comentario', models.TextField(max_length=200, null=True)),
                ('almacenista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.articulo_gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Conceptos_Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('agotado', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, max_length=200, null=True)),
                ('concepto_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.entrada_gasto_ajuste')),
            ],
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto'),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario'),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto'),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='subproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto'),
        ),
    ]
