# Generated by Django 4.2.4 on 2023-10-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo_gasto',
            name='entrada_salida_express',
        ),
        migrations.RemoveField(
            model_name='articulo_gasto',
            name='factura_pdf',
        ),
        migrations.RemoveField(
            model_name='articulo_gasto',
            name='factura_xml',
        ),
        migrations.RemoveField(
            model_name='solicitud_gasto',
            name='approved_at_time',
        ),
        migrations.RemoveField(
            model_name='solicitud_gasto',
            name='approved_at_time2',
        ),
        migrations.RemoveField(
            model_name='solicitud_gasto',
            name='created_at_time',
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='comentariotesorero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.sector'),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='approbado_fecha2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
