# Generated by Django 4.2.4 on 2023-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_rename_area_solicitud_gasto_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='comentario',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
