# Generated by Django 4.2.4 on 2023-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_articulo_gasto_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='comentario',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_gasto',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
