# Generated by Django 4.2.4 on 2023-10-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activo_codigo_alter_activo_cuenta_contable_and_more'),
        ('gastos', '0006_alter_articulo_gasto_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.activo'),
        ),
    ]
