# Generated by Django 4.2.4 on 2023-10-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activo_codigo_alter_activo_cuenta_contable_and_more'),
        ('gastos', '0007_articulo_gasto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
