# Generated by Django 4.2.4 on 2023-10-27 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_alter_factura_archivo_pdf_alter_factura_archivo_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturastb', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='xmltb', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
