# Generated by Django 4.2.4 on 2023-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_alter_factura_archivo_pdf_alter_factura_archivo_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada_gasto_ajuste',
            name='completado_hora',
        ),
        migrations.AlterField(
            model_name='entrada_gasto_ajuste',
            name='completado_fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
