# Generated by Django 5.0 on 2023-12-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_historicalorder_approved_at_time_and_more'),
        ('gastos', '0011_remove_entrada_gasto_ajuste_completado_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='comentariotesorero',
            field=models.TextField(blank=True, null=True),
        ),
    ]
