# Generated by Django 5.0 on 2024-01-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0013_alter_solicitud_gasto_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
