# Generated by Django 5.0.1 on 2024-02-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0014_factura_hecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje_iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='iva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.porcentaje_iva'),
        ),
    ]
