# Generated by Django 5.0.1 on 2024-02-03 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0015_porcentaje_iva_articulo_gasto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.porcentaje_iva'),
        ),
    ]
