# Generated by Django 5.0.1 on 2024-03-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0017_alter_articulo_gasto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
