# Generated by Django 5.0 on 2024-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0018_alter_articulo_gasto_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
