# Generated by Django 5.0 on 2024-04-03 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0019_factura_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='gastos.solicitud_gasto'),
        ),
    ]
