# Generated by Django 5.0 on 2024-06-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0020_alter_articulo_gasto_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_repetida',
            field=models.BooleanField(default=False),
        ),
    ]
