# Generated by Django 5.0.1 on 2024-06-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0021_factura_es_repetida'),
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='autorizado_por2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='user.profile'),
        ),
    ]
