# Generated by Django 5.0.1 on 2024-07-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_historicalproveedor_direcciones_moneda_and_more'),
        ('gastos', '0022_solicitud_gasto_autorizado_por2'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor_direcciones'),
        ),
    ]
