# Generated by Django 5.0 on 2024-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0023_solicitud_gasto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_gasto',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
