# Generated by Django 5.0.1 on 2024-09-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0024_alter_tipo_gasto_tipo'),
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='verificacion_facturas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rh', to='user.profile'),
        ),
    ]
