# Generated by Django 5.0 on 2024-09-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0025_solicitud_gasto_verificacion_facturas'),
        ('solicitudes', '0005_alter_proyecto_cuenta_contable'),
        ('user', '0010_rename_sustituto_de_profile_sustituto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.sector'),
        ),
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='verificacion_facturas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rh', to='user.profile'),
        ),
    ]
