# Generated by Django 5.0.1 on 2024-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0026_alter_solicitud_gasto_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
