# Generated by Django 5.0 on 2024-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0027_factura_fecha_timbrado_factura_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
