# Generated by Django 5.0 on 2024-11-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0028_alter_factura_uuid'),
        ('user', '0011_customuser_apoyo_mantto_customuser_apoyo_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='autorizada',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='autorizada_el',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='autorizada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizado_factura_gasto', to='user.profile'),
        ),
    ]
