# Generated by Django 5.0 on 2024-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0029_factura_autorizada_factura_autorizada_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='inicio_form',
            field=models.DateTimeField(null=True),
        ),
    ]
