# Generated by Django 5.0.1 on 2025-04-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0031_factura_estado_sat_factura_fecha_validacion_sat'),
        ('user', '0022_profile_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeRosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('esta_aprobado', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_rosa_aprobado', to='user.profile')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_rosa_creado', to='user.profile')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_rosa', to='gastos.solicitud_gasto')),
            ],
        ),
    ]
