# Generated by Django 5.0.1 on 2025-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0032_valerosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valerosa',
            name='esta_aprobado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
