# Generated by Django 5.0 on 2025-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0033_alter_valerosa_esta_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='transferencia_finanzas',
            field=models.BooleanField(default=False),
        ),
    ]
