# Generated by Django 5.0 on 2025-05-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0034_solicitud_gasto_transferencia_finanzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArchivoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='nomina/')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.tipoarchivonomina')),
            ],
        ),
    ]
