# Generated by Django 5.0 on 2025-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0035_tipoarchivonomina_archivonomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivonomina',
            name='archivo',
            field=models.FileField(upload_to='nomina'),
        ),
    ]
