# Generated by Django 5.0 on 2025-06-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0036_alter_archivonomina_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_gasto',
            name='familia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
