# Generated by Django 5.0 on 2025-06-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0037_tipo_gasto_familia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoArchivoNomina',
            new_name='TipoArchivoSoporte',
        ),
        migrations.CreateModel(
            name='ArchivoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='soportes')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.tipoarchivosoporte')),
            ],
        ),
        migrations.DeleteModel(
            name='ArchivoNomina',
        ),
    ]
