# Generated by Django 5.0 on 2025-06-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0038_rename_tipoarchivonomina_tipoarchivosoporte_and_more'),
        ('user', '0024_tipo_perfil_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='cerrar_sin_pago_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='persona_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cierre_Gasto', to='user.profile'),
        ),
    ]
