# Generated by Django 5.0 on 2025-06-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0039_solicitud_gasto_cerrar_sin_pago_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
