# Generated by Django 5.0 on 2025-06-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0040_solicitud_gasto_comentario_cierre'),
        ('viaticos', '0041_solicitud_viatico_cerrar_sin_pago_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerosa',
            name='viatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_rosa_viatico', to='viaticos.solicitud_viatico'),
        ),
        migrations.AlterField(
            model_name='valerosa',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_rosa', to='gastos.solicitud_gasto'),
        ),
    ]
