# Generated by Django 5.0 on 2025-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0041_valerosa_viatico_alter_valerosa_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='dispersion',
            field=models.BooleanField(default=False),
        ),
    ]
