# Generated by Django 5.0 on 2025-08-12 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0043_solicitud_gasto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerosa',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_vales', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
