# Generated by Django 5.0 on 2025-12-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0044_valerosa_comprobante_pdf'),
        ('user', '0026_tipo_perfil_cuentas_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='manda_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manda_pago_gasto', to='user.profile'),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='para_pago',
            field=models.BooleanField(default=False),
        ),
    ]
