# Generated by Django 5.0 on 2025-12-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0045_solicitud_gasto_manda_pago_solicitud_gasto_para_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
