# Generated by Django 5.0 on 2025-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0046_solicitud_gasto_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='cerrar_facturacion',
            field=models.BooleanField(default=False),
        ),
    ]
