# Generated by Django 5.0 on 2026-01-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0047_solicitud_gasto_cerrar_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerosa',
            name='color',
            field=models.CharField(choices=[('rosa', 'Rosa'), ('azul', 'Azul')], default='rosa', max_length=10),
        ),
    ]
