# Generated by Django 5.0 on 2026-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0048_valerosa_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerosa',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
