# Generated by Django 5.0 on 2026-09-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0049_valerosa_fecha_pago'),
        ('solicitudes', '0014_contrato_tiene_pozos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='pozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_gastos', to='solicitudes.pozo'),
        ),
    ]
